// Icon names used by the project data files resolve through this map, so
// data/projects/*.js can stay plain data with no imports.
import {
  Activity,
  ArrowDownWideNarrow,
  BarChart3,
  Bot,
  Building2,
  CalendarCheck,
  CircleCheckBig,
  Download,
  Eye,
  FileText,
  KeyRound,
  LayoutDashboard,
  Link2,
  ListOrdered,
  MessagesSquare,
  Mic,
  MousePointerClick,
  Palette,
  Scissors,
  Send,
  Share2,
  Sparkles,
  Stethoscope,
  UserRoundCheck,
  Users,
  Wrench,
} from 'lucide-react'

const ICONS = {
  Activity,
  ArrowDownWideNarrow,
  BarChart3,
  Bot,
  Building2,
  CalendarCheck,
  CircleCheckBig,
  Download,
  Eye,
  FileText,
  KeyRound,
  LayoutDashboard,
  Link2,
  ListOrdered,
  MessagesSquare,
  Mic,
  MousePointerClick,
  Palette,
  Scissors,
  Send,
  Share2,
  Stethoscope,
  UserRoundCheck,
  Users,
  Wrench,
}

export const icon = (name) => ICONS[name] || Sparkles
